### ISSUE TITLE
Using python=3.6.6, it seems that the installation cannot be completed.

### ISSUE THREAD

**Issue by pipishanh** [Barabasi-Lab/AI-Bind#1]
Great work, I can’t wait to apply AI-Bind to evaluate the binding ability of short peptides and proteins. However I can't seem to complete the correct installation using python 3.6.6.

ERROR: Ignored the following versions that require a different python version: 1.0.7 Requires-Python >=3.8; 1.1.0 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement contourpy==1.0.7 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6)
ERROR: No matching distribution found for contourpy==1.0.7

**Comment by ChatterjeeAyan** [comment]
Thanks for pointing this out. Please try the installation without contourpy or using a version of contourpy compatible with Python 3.6.6. Installing Matplotlib should also suffice the requirements. 

You can also use this docker: https://hub.docker.com/r/omairs/foodome2

**Comment by ChatterjeeAyan** [comment]
>> I can’t wait to apply AI-Bind to evaluate the binding ability of short peptides and proteins.

AI-Bind predicts binding between small molecules and proteins. You would need to use a protein-protein interaction prediction model for your purpose.
