### ISSUE TITLE
How to inference with new data?

### ISSUE THREAD

**Issue by Christinele14** [Barabasi-Lab/AI-Bind#4]
Thank you so much for your meaningful work. I am intending to use AI-Bind to inference with new protein and new ligand. However, I am wondering how could I prepare data to inference using AI-Bind model? Could you give me instruction? Thank you so much in advance.

**Comment by ChatterjeeAyan** [comment]
Hi Christinele,

Thanks for your interest in our work. First set up the environment using the docket mentioned on our GitHub: https://hub.docker.com/r/omairs/foodome2. Thereafter, follow the front-end Jupyter notebook: https://github.com/Barabasi-Lab/AI-Bind/blob/main/VecNet-User-Frontend.ipynb. You need to provide 3 columns in your dataframe:

nodes_df = pd.DataFrame()
nodes_df['InChiKey'] = ['HUMNYLRZRPPJDN-UHFFFAOYSA-N'] # List of InChiKeys
nodes_df['SMILE'] = ['C1=CC=C(C=C1)C=O'] # List of SMILES
nodes_df['target_aa_code'] = sars_targets['Sequence'].tolist()[0] # List of amino acid sequences 

After you run AI-Bind on this dataframe, you will get the predicted binding probabilities in a column named 'Averaged Predictions'.

Hope this helps!

**Comment by Christinele14** [comment]
Hi ChatterjeeAyan,

Thank you for your quick response and detailed instruction to help me do inference in new data. After some struggles, I finally could run AI-Bind to get predicted binding probabilities in new data. It really helps. Thank you!
